# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift-Test


on:
  #push:
  #  branches: [ "develop" ]
  pull_request:
    branches: [ "develop", "main" ]
    types: [opened, synchronize]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Swift
      # You may pin to the exact commit or the version.
      # uses: swift-actions/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf
      uses: swift-actions/setup-swift@v1.26.0
      with:
        # Swift version to configure
        swift-version: 5.8.0
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
